batch_size: 64
dropout: 0.2
hidden_size: 128
learning_rate: 1.0e-05
multi_label: true
n_features: 100
num_layers: 4
output_size: 5
pos_w: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADI4MzM0MzE2OHECWAMAAABjcHVxA0sFTnRxBFEugAJdcQBYCQAAADI4MzM0MzE2
    OHEBYS4FAAAAAAAAAJ+3SUBjliNABA0XQHd3s0C96QVC
- 0
- !!python/tuple
  - 5
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
